export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const MAZE_REQUEST = 'MAZE_REQUEST'
export const MAZE_REQUEST_RESOLVE = 'MAZE_REQUEST_RESOLVE'
export const MAZE_REQUEST_DELETE = 'MAZE_REQUEST_DELETE'